### ISSUE TITLE
ERROR: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by maxbambi** [kodiondemand/kodiondemand.github.io#3]
I don't know why I got this error in my kodi installation (Kodi 18.5 git 20191117 - Ubuntu 16.04.6 LTS) , even if I made a clean reinstall.
```
2020-01-23 20:41:31.924 T:140471535924992   ERROR: ######## ERROR #########
2020-01-23 20:41:31.924 T:140471535924992   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/massimo/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/massimo/.kodi/addons/plugin.video.kod/core/support.py", line 381, in wrapper
                                                page = httptools.downloadpage(item.url, headers=headers, ignore_response_code=True, session=item.session)
                                              File "/home/massimo/.kodi/addons/plugin.video.kod/core/httptools.py", line 269, in downloadpage
                                                session.mount('https://', resolverdns.CipherSuiteAdapter(domain, CF))
                                              File "/home/massimo/.kodi/addons/plugin.video.kod/specials/resolverdns.py", line 43, in __init__
                                                self.ssl_context = CustomContext(ssl.PROTOCOL_TLS if 'PROTOCOL_TLS' in ssl.__dict__ else ssl.PROTOCOL_SSLv3, domain)
                                            AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by mac12m99** [comment]
Ciao, mi spiace ma hai l'aperto l'issue sul progetto sbagliato e non ce ne siamo accorti :(
Comunque quel problema me lo ricordo e dovrebbe essere stato fixato, se hai ancora problemi apri l'issue sul repo "addon"
